У цьому домашньому завданні ми будемо працювати з набором даних Tips. Нижче інформація про нього.

**Про датасет:**

Tips - це датасет, який містить інформацію про рахунки та чайові в ресторані.

**Колонки датасету:**
- `total_bill` - загальна сума рахунку (долари)
- `tip` - розмір чайових (долари)
- `sex` - стать відвідувача (Male/Female)
- `smoker` - чи курить (Yes/No)
- `day` - день тижня (Thur/Fri/Sat/Sun)
- `time` - час відвідування (Lunch/Dinner)
- `size` - розмір групи (кількість людей)

**Джерело:** Оригінальні дані зібрані в одному з американських ресторанів у 1990-х роках. Скачати і переглянути набір даних можна тут: https://www.kaggle.com/datasets/sakshisatre/tips-dataset

А також ми вже вивантажили файл з даними і завантажили вам у Матеріали до цього модуля.




**1. Завантаження та огляд**

Завантажте датасет Tips (Чайові) з файла у матеріалах `tips.csv`.

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перші 5 рядків
- Розмір датасету (shape)
- Назви всіх колонок
- Інформацію про типи даних (info)

In [1]:
import pandas as pd

df = pd.read_csv('tips.csv')

display(df.head())
display(df.shape)
display(df.columns)
display(df.info())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

(244, 7)

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

None

**2. Базова вибірка даних**

Виберіть та виведіть (кожен пункт оцінюється в 0.5 бала):
- Колонку `total_bill` (загальний рахунок)
- Колонки `total_bill` та `tip` (чайові) разом
- Перші 10 рядків
- Рядок з індексом 5

In [2]:
display(df['total_bill'])
display(df[['total_bill', 'tip']])
display(df.iloc[0:10])
display(df.iloc[5])

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

**3. Фільтрація даних**

Відфільтруйте повний набір даних та виведіть (кожен пункт оцінюється в 0.5 бала):
- Всі рахунки більше 20 доларів (`total_bill > 20`)
- Всі відвідувачі-жінки (`sex == 'Female'`)
- Рахунки на вечерю (`time == 'Dinner'`)
- Рахунки на вечерю з сумою чеку більше 30 доларів

Для виведення результатів фільтрації:
- зберегти результат у окрему змінну
- показати кількість записів у відфільтрованому наборі
- вивести перші 5 записів відфільтрованого набору.

In [3]:
print("All bills greater than 20$")
display(df[df['total_bill'] > 20])
print("All women customers")
display(df[df['sex'] == 'Female'])
print("All dinner bills")
display(df[df['time'] == 'Dinner'])
print("All dinner bills greater than 30$")
display(df[(df['time'] == 'Dinner') & (df['total_bill'] > 30)])

All bills greater than 20$

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

All women customers

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

All dinner bills

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

All dinner bills greater than 30$

     total_bill    tip     sex smoker  day    time  size
11        35.26   5.00  Female     No  Sun  Dinner     4
23        39.42   7.58    Male     No  Sat  Dinner     4
39        31.27   5.00    Male     No  Sat  Dinner     3
44        30.40   5.60    Male     No  Sun  Dinner     4
47        32.40   6.00    Male     No  Sun  Dinner     4
52        34.81   5.20  Female     No  Sun  Dinner     4
56        38.01   3.00    Male    Yes  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
95        40.17   4.73    Male    Yes  Fri  Dinner     4
102       44.30   2.50  Female    Yes  Sat  Dinner     3
112       38.07   4.00    Male     No  Sun  Dinner     3
156       48.17   5.00    Male     No  Sun  Dinner     6
167       31.71   4.50    Male     No  Sun  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
173       31.85   3.18    Male    Yes  Sun  Dinner     2
175       32.90   3.11    Male    Yes  Sun  Dinner     2
179       34.63   3.55    Male    Yes  Sun  Dinner     2
180       34.65   3.68    Male    Yes  Sun  Dinner     4
182       45.35   3.50    Male    Yes  Sun  Dinner     3
184       40.55   3.00    Male    Yes  Sun  Dinner     2
187       30.46   2.00    Male    Yes  Sun  Dinner     5
207       38.73   3.00    Male    Yes  Sat  Dinner     4
210       30.06   2.00    Male    Yes  Sat  Dinner     3
212       48.33   9.00    Male     No  Sat  Dinner     4
219       30.14   3.09  Female    Yes  Sat  Dinner     4
237       32.83   1.17    Male    Yes  Sat  Dinner     2
238       35.83   4.67  Female     No  Sat  Dinner     3

---

**4. Описова статистика**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній розмір рахунку на всьому наборі даних
- Максимальні чайові
- Кількість пропущених значень у всіх колонках
- Скільки в наборі даних рахунків за обіди і за вечері

In [4]:
print(f"Total bill mean is {df.total_bill.mean()}")
print(f"Maximum tip is {df.tip.max()}")
print(f"Number of missing values in all columns: \n{df.isnull().sum()}")
print(f"Number of dinner bills is {(df['time'] == 'Dinner').astype(int).sum()}")
print(f"Number of lunch bills is {(df['time'] == 'Lunch').astype(int).sum()}")
print(f"Total number of dinner and lunch bills is {df['time'].isin(['Lunch', 'Dinner']).astype(int).sum()}")

Total bill mean is 19.78594262295082
Maximum tip is 10.0
Number of missing values in all columns:
total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64
Number of dinner bills is 176
Number of lunch bills is 68
Total number of dinner and lunch bills is 244

---

**5. Статистика із групуванням**

Обчисліть (кожен пункт оцінюється в 0.5 бала):
- Середній рахунок за статтю (groupby `sex`)
- Середні чайові за днем тижня (groupby `day`)
- Скільки відвідувачів у кожен день

In [5]:
print("Average bill by sex:")
display(df.groupby('sex')['total_bill'].mean())
print("\nAverage tip by day:")
display(df.groupby('day')['tip'].mean())
print("\nNumber of customers per day:")
display(df.groupby('day').size())

Average bill by sex:

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

Average tip by day:

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

Number of customers per day:

day
Fri     19
Sat     87
Sun     76
Thur    62
dtype: int64

---

**6. Створення нової колонки**

Створіть нову колонку `tip_percentage` - відсоток чайових від загальної суми рахунку.
Виведіть перші 10 рядків з новою колонкою.

In [6]:
df['tip_percentage'] = (100 * (df['tip'] / df['total_bill'])).round(2)
display(df[['tip_percentage']].head(10))

   tip_percentage
0            5.94
1           16.05
2           16.66
3           13.98
4           14.68
5           18.62
6           22.81
7           11.61
8           13.03
9           21.85

---

**7. Сортування**

Відсортуйте датасет і виведіть результат сортування в кожному випадку окремо (кожен пункт оцінюється в 0.5 бала):
- За розміром рахунку (зростання)
- За чайовими (спадання)

Додатково виведіть топ-5 найбільших чайових використовуючи метод `nlargest`.

In [7]:
print("Sorted by bill:")
display(df.sort_values('total_bill'))
print("\nSorted by tip (desc):")
display(df.sort_values('tip', ascending=False))
print("\nTop-5 tips:")
display(df.nlargest(5, 'tip'))

Sorted by bill:

     total_bill    tip     sex smoker   day    time  size  tip_percentage
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
172        7.25   5.15    Male    Yes   Sun  Dinner     2           71.03
149        7.51   2.00    Male     No  Thur   Lunch     2           26.63
..          ...    ...     ...    ...   ...     ...   ...             ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3            7.72
156       48.17   5.00    Male     No   Sun  Dinner     6           10.38
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68

[244 rows x 8 columns]

Sorted by tip (desc):

     total_bill    tip     sex smoker   day    time  size  tip_percentage
170       50.81  10.00    Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00    Male     No   Sat  Dinner     4           18.62
23        39.42   7.58    Male     No   Sat  Dinner     4           19.23
59        48.27   6.73    Male     No   Sat  Dinner     4           13.94
141       34.30   6.70    Male     No  Thur   Lunch     6           19.53
..          ...    ...     ...    ...   ...     ...   ...             ...
0         16.99   1.01  Female     No   Sun  Dinner     2            5.94
111        7.25   1.00  Female     No   Sat  Dinner     1           13.79
92         5.75   1.00  Female    Yes   Fri  Dinner     2           17.39
67         3.07   1.00  Female    Yes   Sat  Dinner     1           32.57
236       12.60   1.00    Male    Yes   Sat  Dinner     2            7.94

[244 rows x 8 columns]

Top-5 tips:

     total_bill    tip   sex smoker   day    time  size  tip_percentage
170       50.81  10.00  Male    Yes   Sat  Dinner     3           19.68
212       48.33   9.00  Male     No   Sat  Dinner     4           18.62
23        39.42   7.58  Male     No   Sat  Dinner     4           19.23
59        48.27   6.73  Male     No   Sat  Dinner     4           13.94
141       34.30   6.70  Male     No  Thur   Lunch     6           19.53